# Uncomment the next line to define a global platform for your project
 platform :ios, '14.4'

target 'GNBCatalog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GNBCatalog
  pod 'SwiftLint'

  target 'GNBCatalogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GNBCatalogUITests' do
    # Pods for testing
  end

end
